name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install '.[extra]'
        pip install '.[test]'

    - name: Lint code
      run: |
        make lint

    - name: Run tests
      run: |
        make test

    - name: Run coverage
      run: |
        make coverage

    - name: Publish coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
